apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-cluster
spec:
  destination:
    name: ""
    namespace: "default"
    server: "https://kubernetes.default.svc"
  source:
    path: "capi-cluster/aws-eks"
    repoURL: git@github.com:mr-saoirse/test.git
    targetRevision: HEAD
    #helm:
    # valueFiles:
    # - values-c1.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
#aws eks --region us-west-2 update-kubeconfig --namedefault_capi-eks-control-plane
#aws eks describe-cluster --name default_capi-eks-control-plane-user@default_capi-eks-control-plane --region us-west-2 | jq '.cluster.endpoint'

#kubectl apply -f ./management/argocd-eks-dev.yaml
#kubectl get clusters
