apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-cluster-dev
spec:
  destination:
    name: "test"
    namespace: "default"
    server: "https://kubernetes.default.svc"
  source:
    path: "capi-cluster/aws-eks"
    repoURL: git@github.com:mr-saoirse/test.git
    targetRevision: HEAD
    #helm:
    # valueFiles:
    # - values-c1.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
#
