metadata:
  name: argo
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: test
  source:
    path: argo/production
    repoURL: git@github.com:mr-saoirse/test.git
    targetRevision: HEAD
