apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: argo
  name: argo-server
spec:
  template:
    spec:
      containers:
        - args:
            - server
            - '--secure=false'
            - '--auth-mode=server'
          name: argo-server
          readinessProbe:
            httpGet:
              path: /
              port: 2746
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20